use crate::surrogate::SurrogateHandle;
use crate::surrogate::aero_surrogate::query_aero;
use crate::types::{DroneState, SurrogateQueryResult, VehicleConfig};
use glam::{DQuat, DVec3};

const DRAG_COEFF_X: f64 = 1.0;
const DRAG_COEFF_Y: f64 = 1.0;
const DRAG_COEFF_Z: f64 = 1.5;

const FRONTAL_AREA_X: f64 = 0.02;
const FRONTAL_AREA_Y: f64 = 0.02;
const FRONTAL_AREA_Z: f64 = 0.08;

const STD_TEMP: f64 = 288.15;
const STD_PRESSURE: f64 = 101325.0;
const TEMP_LAPSE_RATE: f64 = 0.0065;
const SPECIFIC_GAS_CONST: f64 = 287.05;
const GRAVITY: f64 = 9.80665;

#[derive(Debug)]
pub enum AeroError {
    AltitudeOutOfRange,
}

/// Computes the air density at a given altitude using the International Standard Atmosphere (ISA) model.
fn compute_air_density(altitude: f64) -> Result<f64, AeroError> {
    if !(0.0..=11000.0).contains(&altitude) {
        return Err(AeroError::AltitudeOutOfRange);
    }
    let temp_at_alt = STD_TEMP - (TEMP_LAPSE_RATE * altitude);
    let exponent = GRAVITY / (SPECIFIC_GAS_CONST * TEMP_LAPSE_RATE);

    let pressure_ratio = (temp_at_alt / STD_TEMP).powf(exponent);
    let pressure_at_alt = STD_PRESSURE * pressure_ratio;

    Ok(pressure_at_alt / (SPECIFIC_GAS_CONST * temp_at_alt))
}

/// Computes the aerodynamic drag force vector.
pub fn get_drag(state: &DroneState, altitude: f64) -> Result<[f32; 3], AeroError> {
    let density = compute_air_density(altitude)?;

    let vel_world = DVec3::new(
        state.velocity[0] as f64,
        state.velocity[1] as f64,
        state.velocity[2] as f64,
    );
    let rot_world = DQuat::from_xyzw(
        state.orientation[0] as f64,
        state.orientation[1] as f64,
        state.orientation[2] as f64,
        state.orientation[3] as f64,
    );

    let vel_body = rot_world.inverse() * vel_world;

    let calc_axis_drag = |v: f64, coeff: f64, area: f64| -> f64 {
        if v == 0.0 {
            return 0.0;
        }
        -0.5 * density * v.powi(2) * v.signum() * coeff * area
    };

    let drag_body = DVec3::new(
        calc_axis_drag(vel_body.x, DRAG_COEFF_X, FRONTAL_AREA_X),
        calc_axis_drag(vel_body.y, DRAG_COEFF_Y, FRONTAL_AREA_Y),
        calc_axis_drag(vel_body.z, DRAG_COEFF_Z, FRONTAL_AREA_Z),
    );

    let drag_world = rot_world * drag_body;

    Ok([
        drag_world.x as f32,
        drag_world.y as f32,
        drag_world.z as f32,
    ])
}

/// Computes the thrust generated by a single propeller.
pub fn get_thrust(throttle: f32, config: &VehicleConfig) -> Result<f32, AeroError> {
    let density = compute_air_density(0.0)?;
    let clamped_throttle = (throttle as f64).clamp(0.0, 1.0);
    let rps = (clamped_throttle * config.max_rpm) / 60.0;

    let thrust = config.thrust_coeff * density * rps.powi(2) * config.prop_diameter_m.powi(4);
    Ok(thrust as f32)
}

/// Calculates aerodynamic drag, utilizing the surrogate model if available,
/// or falling back to the Phase 1 analytical ISA model.
pub fn get_drag_with_fallback(
    state: &DroneState,
    altitude: f64,
    aero_handle: Option<&mut SurrogateHandle>,
) -> Result<([f32; 3], Option<SurrogateQueryResult>), AeroError> {
    if let Some(handle) = aero_handle
        && let Ok(result) = query_aero(handle, state)
    {
        return Ok((result.predicted_values, Some(result)));
    }

    Ok((get_drag(state, altitude)?, None))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dummy_config() -> VehicleConfig {
        VehicleConfig {
            mass_kg: 1.0,
            inertia_kgm2: [1.0, 1.0, 1.0],
            motor_pos_m: [
                [0.2, 0.2, 0.0],
                [0.2, -0.2, 0.0],
                [-0.2, 0.2, 0.0],
                [-0.2, -0.2, 0.0],
            ],
            motor_spin: [1.0, -1.0, -1.0, 1.0],
            prop_diameter_m: 0.25,
            thrust_coeff: 0.11,
            torque_coeff: 0.05,
            max_rpm: 10000.0,
            hover_throttle: 0.4095,
        }
    }

    #[test]
    fn test_b1_isa_values() {
        let cases = [
            (0.0, 1.2250),
            (500.0, 1.16727),
            (1000.0, 1.11164),
            (5000.0, 0.73611),
            (11000.0, 0.36391),
        ];
        for (alt, expected) in cases {
            let density = compute_air_density(alt).unwrap();
            assert!(
                (density - expected).abs() / expected < 1e-4,
                "Failed at {}m. Expected {}, got {}",
                alt,
                expected,
                density
            );
        }
    }

    #[test]
    fn test_b3_density_decreases_with_altitude() {
        assert!(compute_air_density(500.0).unwrap() < compute_air_density(0.0).unwrap());
        assert!(compute_air_density(1000.0).unwrap() < compute_air_density(500.0).unwrap());
    }

    #[test]
    fn test_b4_troposphere_limit() {
        let d = compute_air_density(11000.0).unwrap();
        assert!(d > 0.0 && d < 1.225);
        assert!(!d.is_nan());
        assert!(compute_air_density(12000.0).is_err());
    }

    #[test]
    fn test_b2_altitude_500m() {
        let d = compute_air_density(500.0).unwrap();
        assert!((d - 1.167).abs() < 0.005);
    }

    #[test]
    fn test_c1_zero_velocity() {
        let state = DroneState {
            position: [0.0, 0.0, 0.0],
            velocity: [0.0, 0.0, 0.0],
            orientation: [0.0, 0.0, 0.0, 1.0],
            angular_velocity: [0.0, 0.0, 0.0],
        };
        assert_eq!(get_drag(&state, 0.0).unwrap(), [0.0, 0.0, 0.0]);
    }

    #[test]
    fn test_c2_drag_opposes_motion() {
        let state_x = DroneState {
            position: [0.0, 0.0, 0.0],
            velocity: [5.0, 0.0, 0.0],
            orientation: [0.0, 0.0, 0.0, 1.0],
            angular_velocity: [0.0, 0.0, 0.0],
        };
        assert!(get_drag(&state_x, 0.0).unwrap()[0] < 0.0);
    }

    #[test]
    fn test_c3_drag_scales_with_velocity_squared() {
        let state_5 = DroneState {
            position: [0.0, 0.0, 0.0],
            velocity: [5.0, 0.0, 0.0],
            orientation: [0.0, 0.0, 0.0, 1.0],
            angular_velocity: [0.0, 0.0, 0.0],
        };
        let state_10 = DroneState {
            position: [0.0, 0.0, 0.0],
            velocity: [10.0, 0.0, 0.0],
            orientation: [0.0, 0.0, 0.0, 1.0],
            angular_velocity: [0.0, 0.0, 0.0],
        };
        let drag_5 = get_drag(&state_5, 0.0).unwrap()[0].abs();
        let drag_10 = get_drag(&state_10, 0.0).unwrap()[0].abs();
        assert!((drag_10 - (drag_5 * 4.0)).abs() < 0.1);
    }

    #[test]
    fn test_c4_different_axes_different_drag() {
        let drag_x = get_drag(
            &DroneState {
                position: [0.0, 0.0, 0.0],
                velocity: [10.0, 0.0, 0.0],
                orientation: [0.0, 0.0, 0.0, 1.0],
                angular_velocity: [0.0, 0.0, 0.0],
            },
            0.0,
        )
        .unwrap()[0]
            .abs();
        let drag_z = get_drag(
            &DroneState {
                position: [0.0, 0.0, 0.0],
                velocity: [0.0, 0.0, 10.0],
                orientation: [0.0, 0.0, 0.0, 1.0],
                angular_velocity: [0.0, 0.0, 0.0],
            },
            0.0,
        )
        .unwrap()[2]
            .abs();
        assert!(drag_z > drag_x);
    }

    #[test]
    fn test_d1_zero_throttle() {
        let cfg = dummy_config();
        assert_eq!(get_thrust(0.0, &cfg).unwrap(), 0.0);
    }

    #[test]
    fn test_d2_thrust_scales_with_throttle_squared() {
        let cfg = dummy_config();
        let t_025 = get_thrust(0.25, &cfg).unwrap();
        let t_050 = get_thrust(0.5, &cfg).unwrap();
        assert!((t_050 - (t_025 * 4.0)).abs() < 0.1);
    }

    #[test]
    fn test_d5_throttle_clamping() {
        let cfg = dummy_config();
        assert_eq!(
            get_thrust(-0.5, &cfg).unwrap(),
            get_thrust(0.0, &cfg).unwrap()
        );
        assert_eq!(
            get_thrust(1.5, &cfg).unwrap(),
            get_thrust(1.0, &cfg).unwrap()
        );
    }
}
